### ISSUE TITLE
gulp error - Cannot find module 'jstransform/node_modules/esprima-fb'

### ISSUE THREAD

**Issue by lucanos** [NSWSESMembers/Lighthouse#36]
Followed the instructions in the commonjs readme, but keep seeing this error. Happens on Mac & Win.

$ gulp
module.js:329
    throw err;
    ^

Error: Cannot find module 'jstransform/node_modules/esprima-fb'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (F:\GitHub\Lighthouse\node_modules\jsx-transform\lib\visitor.js:1:14)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)

![screenshot_7](https://cloud.githubusercontent.com/assets/126774/12147912/9c903814-b4ef-11e5-91df-811df2c7ee63.png)

**Comment by lucanos** [comment]
I was able to fix it, but only after running `npm install jstransform`
